- name: Launch instance
  ec2: key_name={{ keypair }} group={{ group }} instance_type={{ instance_type }} image={{ image }} wait=true region={{ region }} spot_price={{ spot_price }}
  register: ec2
- name: Add instance to local host group
  local_action: lineinfile dest=/home/asimon/playbooks/lamp_spot/hosts regexp={{ item.public_dns_name }} insertafter="[webservers]" line="{{ item.public_dns_name }} ansible_ssh_private_key_file=/home/asimon/.ssh/AWSWest.pem"
  with_items: ec2.instances
- name: Wait for SSH to come up
  local_action: wait_for host={{ item.public_dns_name }} port=22 delay=60 timeout=320 state=started
  with_items: ec2.instances
